alias gitaply='git stash apply'
alias gitbr='git branch'
alias gitdf='git diff'
alias gitft='git fetch --all'
alias gitlg='git log --pretty=format:"%C(yellow)%h %C(blue)%ad %C(reset)%s %C(green)%an" --date=short --no-merges'
alias gitlist='git stash list'
alias gitmg='git merge'
alias gitout='git checkout'
alias gitpl='git pull --ff origin'
alias gitps='git push origin'
alias gitsave='git stash save'
alias gitst='git status -uno'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
